config/routes.rb
Rails.application.routes.draw do
  resources :accessories
  resources :jewels
  resources :bases
  #custom users routes
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#login_check'
  get 'users/logout' => 'users#logout'
  resources :users
  resources :designs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/design.rb
class Design < ApplicationRecord
  # relations
  belongs_to :brand

  # validation 
  validates :name, presence: true
  validates :name, length: { minimum: 3 }
  validates :name, uniqueness: { scope: :brand_id,
    message: "that combination should be unique !" }
  validates :brand_id, presence: true 
  validates :brand_id, numericality: { only_integer: true }
  validates :core_number, presence: true
  validates :core_number, numericality: { only_integer: true }
  validates :accent_number, presence: true
  validates :accent_number, numericality: { only_integer: true }
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    if session[:user_id] == nil || @current_user.role != 'admin'
      flash[:notice] = "Sorry, members can't create new designs !"
      redirect_to designs_url
    else
      @design = Design.new
      @brands = Brand.all
    end
  end

  # GET /designs/1/edit
  def edit
    @brands = Brand.all
    if session[:user_id] == nil || @current_user.role != 'admin'
      flash[:notice] = "Sorry but members can't edit designs !"
      redirect_to designs_url
    else
    end
  end

  # POST /designs
  # POST /designs.json
  def create
    if session[:user_id] == nil || @current_user.role != 'admin'
      flash[:notice] = "You shouldn't be here ;) !"
      redirect_to designs_url
    else
      @design = Design.new(design_params)
      @brands = Brand.all

      respond_to do |format|
        if @design.save
          format.html { redirect_to @design, notice: 'Design was successfully created.'}
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.'}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    if session[:user_id] == nil || @current_user.role != 'admin'
      flash[:notice] = "Nope, sorry ;) !"
      redirect_to designs_url
    else
      @design.destroy
      respond_to do |format|
        format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:name, :brand_id, :core_number, :accent_number)
    end

end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_with(model: design, local: true) do |form| %>
  <% if design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :design_name %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.select("brand_id", @brands.collect {|b| [ b.name, b.id ] }, { include_blank: false}) %>
  </div>

  <div class="field">
    <%= form.label :core_number %>
    <%= form.number_field(:core_number, {in: 0..1})%>
  </div>

  <div class="field">
    <%= form.label :accent_number %>
    <%= form.number_field(:accent_number, {in: 0..50 }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand Id</th>
      <th>Core Number</th>
      <th>Accent Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.name%></td>
        <td><%= design.brand.name %></td>
        <td><%= design.core_number%></td>
        <td><%= design.accent_number%></td>
        <% if session[:user_id] != nil && @current_user.role == 'admin' %>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @design.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @design.brand.name %>
</p>

<p>
  <strong>Core Number:</strong>
  <%= @design.core_number %> core
</p>

<p>
  <strong>Accent Number:</strong>
  <%= @design.accent_number %> core
</p>

<% if session[:user_id] != nil && @current_user.role == 'admin' %>
  <%= link_to 'Edit', edit_design_path(@design) %> |
  <%= link_to 'Back', designs_path %>
<% end %>