config/routes.rb
Rails.application.routes.draw do
  resources :accessories
  resources :jewels
  resources :bases
  #custom users routes
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#login_check'
  get 'users/logout' => 'users#logout'
  resources :users
  resources :designs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jewel.rb
class Jewel < ApplicationRecord
  # relations
  belongs_to :design
  belongs_to :material
  belongs_to :locking_system
  belongs_to :brand
  belongs_to :size
  belongs_to :anodizing
  belongs_to :user

  # validation
  validates :design_id, presence: true
  validates :design_id, numericality: { only_integer: true }
  validates :material_id, presence: true
  validates :material_id, numericality: { only_integer: true }
  validates :locking_system_id, presence: true
  validates :locking_system_id, numericality: { only_integer: true }
  validates :brand_id, presence: true
  validates :brand_id, numericality: { only_integer: true }
  validates :size_id, presence: true
  validates :size_id, numericality: { only_integer: true }
  validates :anodizing_id, presence: true
  validates :anodizing_id, numericality: { only_integer: true }
  validates :gemstones_ids, presence: true
  validates :gemstones_ids, length: { minimum: 1 }
  validates :user_id, presence: true
  validates :user_id, numericality: { only_integer: true }
  validates :quantity, presence: true
  validates :quantity, length: { minimum: 1 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_action :set_jewel, only: [:show, :edit, :update, :destroy]

  # GET /jewels
  # GET /jewels.json
  def index
    @jewels = Jewel.all
  end

  # GET /jewels/1
  # GET /jewels/1.json
  def show
  end

  # GET /jewels/new
  def new
    @jewel = Jewel.new
  end

  # GET /jewels/1/edit
  def edit
  end

  # POST /jewels
  # POST /jewels.json
  def create
    @jewel = Jewel.new(jewel_params)

    respond_to do |format|
      if @jewel.save
        format.html { redirect_to @jewel, notice: 'Jewel was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /jewels/1
  # PATCH/PUT /jewels/1.json
  def update
    respond_to do |format|
      if @jewel.update(jewel_params)
        format.html { redirect_to @jewel, notice: 'Jewel was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /jewels/1
  # DELETE /jewels/1.json
  def destroy
    @jewel.destroy
    respond_to do |format|
      format.html { redirect_to jewels_url, notice: 'Jewel was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewel
      @jewel = Jewel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jewel_params
      params.require(:jewel).permit(:design_id, :material_id, :locking_system_id, :brand_id, :size_id, :anodizing_id, :gemstones_ids, :user_id, :quantity)
    end
end

app/helpers/jewels_helper.rb
module JewelsHelper
end

app/views/jewels/_form.html.erb
<%= form_with(model: jewel, local: true) do |form| %>
  <% if jewel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jewel.errors.count, "error") %> prohibited this jewel from being saved:</h2>

      <ul>
      <% jewel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :design_id %>
    <%= form.text_field :design_id, id: :jewel_design_id %>
  </div>

  <div class="field">
    <%= form.label :material_id %>
    <%= form.text_field :material_id, id: :jewel_material_id %>
  </div>

  <div class="field">
    <%= form.label :locking_system_id %>
    <%= form.text_field :locking_system_id, id: :jewel_locking_system_id %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.text_field :brand_id, id: :jewel_brand_id %>
  </div>

  <div class="field">
    <%= form.label :size_id %>
    <%= form.text_field :size_id, id: :jewel_size_id %>
  </div>

  <div class="field">
    <%= form.label :anodizing_id %>
    <%= form.text_field :anodizing_id, id: :jewel_anodizing_id %>
  </div>

  <div class="field">
    <%= form.label :gemstones_ids %>
    <%= form.text_field :gemstones_ids, id: :jewel_gemstones_ids %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :jewel_user_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :jewel_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jewels/edit.html.erb
<h1>Editing Jewel</h1>

<%= render 'form', jewel: @jewel %>

<%= link_to 'Show', @jewel %> |
<%= link_to 'Back', jewels_path %>

app/views/jewels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jewels</h1>

<table>
  <thead>
    <tr>
      <th>Design</th>
      <th>Material</th>
      <th>Locking system</th>
      <th>Brand</th>
      <th>Size</th>
      <th>Anodizing</th>
      <th>Gemstones ids</th>
      <th>User</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jewels.each do |jewel| %>
      <tr>
        <td><%= jewel.design %></td>
        <td><%= jewel.material %></td>
        <td><%= jewel.locking_system %></td>
        <td><%= jewel.brand %></td>
        <td><%= jewel.size %></td>
        <td><%= jewel.anodizing %></td>
        <td><%= jewel.gemstones_ids %></td>
        <td><%= jewel.user %></td>
        <td><%= jewel.quantity %></td>
        <td><%= link_to 'Show', jewel %></td>
        <td><%= link_to 'Edit', edit_jewel_path(jewel) %></td>
        <td><%= link_to 'Destroy', jewel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jewel', new_jewel_path %>

app/views/jewels/new.html.erb
<h1>New Jewel</h1>

<%= render 'form', jewel: @jewel %>

<%= link_to 'Back', jewels_path %>

app/views/jewels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @jewel.design %>
</p>

<p>
  <strong>Material:</strong>
  <%= @jewel.material %>
</p>

<p>
  <strong>Locking system:</strong>
  <%= @jewel.locking_system %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @jewel.brand %>
</p>

<p>
  <strong>Size:</strong>
  <%= @jewel.size %>
</p>

<p>
  <strong>Anodizing:</strong>
  <%= @jewel.anodizing %>
</p>

<p>
  <strong>Gemstones ids:</strong>
  <%= @jewel.gemstones_ids %>
</p>

<p>
  <strong>User:</strong>
  <%= @jewel.user %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @jewel.quantity %>
</p>

<%= link_to 'Edit', edit_jewel_path(@jewel) %> |
<%= link_to 'Back', jewels_path %>