config/routes.rb
Rails.application.routes.draw do
  resources :accessories
  resources :jewels
  resources :bases
  #custom users routes
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#login_check'
  get 'users/logout' => 'users#logout'
  resources :users
  resources :designs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  # relations
  belongs_to :design
  belongs_to :material
  belongs_to :locking_system
  belongs_to :brand
  belongs_to :size
  belongs_to :anodizing
  belongs_to :user

  # validation
  validates :design_id, presence: true
  validates :design_id, numericality: { only_integer: true }
  validates :material_id, presence: true
  validates :material_id, numericality: { only_integer: true }
  validates :locking_system_id, presence: true
  validates :locking_system_id, numericality: { only_integer: true }
  validates :brand_id, presence: true
  validates :brand_id, numericality: { only_integer: true }
  validates :size_id, presence: true
  validates :size_id, numericality: { only_integer: true }
  validates :anodizing_id, presence: true 
  validates :anodizing_id, numericality: { only_integer: true }
  validates :gemstones_ids, presence: true
  validates :gemstones_ids, length: { minimum: 1 }
  validates :user_id, presence: true 
  validates :user_id, numericality: { only_integer: true }
  validates :quantity, presence: true
  validates :quantity, length: { minimum: 1 }
  validates :quantity, numericality: { only_integer: true, minimum: 1 }
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]

  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:design_id, :material_id, :locking_system_id, :brand_id, :size_id, :anodizing_id, :gemstones_ids, :user_id, :quantity)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_form.html.erb
<%= form_with(model: accessory, local: true) do |form| %>
  <% if accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :design_id %>
    <%= form.text_field :design_id, id: :accessory_design_id %>
  </div>

  <div class="field">
    <%= form.label :material_id %>
    <%= form.text_field :material_id, id: :accessory_material_id %>
  </div>

  <div class="field">
    <%= form.label :locking_system_id %>
    <%= form.text_field :locking_system_id, id: :accessory_locking_system_id %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.text_field :brand_id, id: :accessory_brand_id %>
  </div>

  <div class="field">
    <%= form.label :size_id %>
    <%= form.text_field :size_id, id: :accessory_size_id %>
  </div>

  <div class="field">
    <%= form.label :anodizing_id %>
    <%= form.text_field :anodizing_id, id: :accessory_anodizing_id %>
  </div>

  <div class="field">
    <%= form.label :gemstones_ids %>
    <%= form.text_field :gemstones_ids, id: :accessory_gemstones_ids %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :accessory_user_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :accessory_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<h1>Editing Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accessories</h1>

<table>
  <thead>
    <tr>
      <th>Design</th>
      <th>Material</th>
      <th>Locking system</th>
      <th>Brand</th>
      <th>Size</th>
      <th>Anodizing</th>
      <th>Gemstones ids</th>
      <th>User</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.design %></td>
        <td><%= accessory.material %></td>
        <td><%= accessory.locking_system %></td>
        <td><%= accessory.brand %></td>
        <td><%= accessory.size %></td>
        <td><%= accessory.anodizing %></td>
        <td><%= accessory.gemstones_ids %></td>
        <td><%= accessory.user %></td>
        <td><%= accessory.quantity %></td>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>

app/views/accessories/new.html.erb
<h1>New Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Design:</strong>
  <%= @accessory.design %>
</p>

<p>
  <strong>Material:</strong>
  <%= @accessory.material %>
</p>

<p>
  <strong>Locking system:</strong>
  <%= @accessory.locking_system %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @accessory.brand %>
</p>

<p>
  <strong>Size:</strong>
  <%= @accessory.size %>
</p>

<p>
  <strong>Anodizing:</strong>
  <%= @accessory.anodizing %>
</p>

<p>
  <strong>Gemstones ids:</strong>
  <%= @accessory.gemstones_ids %>
</p>

<p>
  <strong>User:</strong>
  <%= @accessory.user %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @accessory.quantity %>
</p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>